name: Update Sponsors

on:
  workflow_dispatch:
  schedule:
    # Every 1 hour
    - cron: '0 * * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    # env name
    environment: sponsorkit
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install deps
        run: npm i --frozen-lockfile

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: xiaodong2008
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update sponsors"
          add: "sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
