name: Update Sponsors

on:
  workflow_dispatch:
  schedule:
    # Every 1 hour
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    # env name
    environment: sponsorkit
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npm install

      - name: Update sponsors
        run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: dy-xiaodong2022

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update sponsors"
          add: "data.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}